# General training settings
model_name: "openai-community/gpt2"  # Model checkpoint
output_dir: "../models/fine_tuned_gpt2"  # Where to save the fine-tuned model
log_dir: "../logs"  # Directory to store training logs

per_device_train_batch_size: 2
per_device_eval_batch_size: 2
num_train_epochs: 3
save_total_limit: 2
save_strategy: "epoch"
evaluation_strategy: "epoch"  # Now we evaluate after each epoch
logging_dir: "logs"
logging_steps: 500
learning_rate: 5e-5
weight_decay: 0.01
