output_dir: "../models/fine_tuned_bart"
log_dir: "../logs/bart"
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
num_train_epochs: 15
save_total_limit: 2
evaluation_strategy: "epoch"
logging_steps: 50
learning_rate: 5e-5
weight_decay: 0.01
