output_dir: "../models/fine_tuned_t5"
log_dir: "../logs/t5"
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
num_train_epochs: 5
save_total_limit: 2
evaluation_strategy: "epoch"
logging_steps: 50
learning_rate: 5e-5
weight_decay: 0.01
max_grad_norm: 1.0
